[package]
name = "p16core-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
circular-buffer = "1.2.0"
hex = "0.4.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
